#!/bin/python3
#Req: Read and show data from students.csv  
# Add a student by name to students.csv  
#   - ID is autogenerated 6 digits
#   - mark is autogenerated between 25 and 100
#   - grade is auto calculated based on the mark 
import csv  
import pandas as pa 
import random as ran 

def read_from_csv():
    with open('students.csv','r') as handler:
        csv_reader = csv.reader(handler)
        for row in csv_reader:
            print(row)

# read_from_csv()

def read_pandas():
    data = pa.read_csv('students.csv')
    print(data)

def random_ID():
    return ran.randint(100000,999999)

def random_mark():
    return ran.randint(25,100)

def auto_grade(mark):
    if mark >= 85:
        grade = 'HD'
    elif mark >= 75:
        grade = 'D'
    elif mark >= 65:
        grade = 'C'
    elif mark >= 50:
        grade = 'P'
    else:
        grade = 'Z'
    return grade

def write_to_csv():
    name = input('Student name: ')
    mark = random_mark()
    row = [random_ID(),name,mark,auto_grade(mark)]
    with open('students.csv','a',newline='') as handler:
        csv_writer = csv.writer(handler)
        csv_writer.writerow(row)

write_to_csv()
read_pandas()


